config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers:{ registrations: "registrations"}
  root to: "adverts#index"

  resources :users, only: [:show]

  resources :adverts


  get  "offres",   to: "adverts#offers"
  get  "demandes", to: "adverts#demandes"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_attachments :photos, maximum: 3
  validates :title, presence: true, length: {minimum: 15}
  validates :description, presence: true, length: {minimum: 80}
  validates :price, presence: true
  validates :location, presence: true
  enum role: { Demande: 0, Offre: 1}

  def self.search(search)
    if search
     where(["lower(title) LIKE ?","%#{search.downcase}%"]).order('created_at DESC')
    else
      all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :adverts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  enum role: {Particulier: 0, Professionnel: 1}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :adverts
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  def index
    filter_adverts if params[:query].present?
    @adverts ||= Advert.all
  end

  def offers
    @adverts = Advert.all.where(role: 1)
  end

  def demandes
    @adverts = Advert.all.where(role: 0)
  end

  def show
    @advert = Advert.find(params[:id])
  end

  def new
    @advert = Advert.new
  end

  def create
    @advert = Advert.new(params_advert)
    @advert.user = current_user
    if @advert.save
      redirect_to advert_path(@advert)
    else
      render :new
    end
  end

  def  destroy
    @advert.destroy
  end

  def edit
  end


  def update
    if @advert.update(advert_params)
      redirect_to advert_path(@advert)
    else
      render :edit
    end
  end

  private

  def params_advert
    params.require(:advert).permit(:type, :title, :description, :location, :price, :role, :category_id, photos: [])
  end

  def set_advert
    @advert = Advert.find(params[:id])
  end

  def filter_adverts
    @adverts = Advert.search(params[:query][:keyword]).includes(:category) if params[:query][:keyword].present?
    @adverts = Advert.joins(:category).where('categories.name LIKE ?', params[:query][:category]) if params[:query][:category].present?
    @adverts = Advert.where('location LIKE ?', params[:query][:location]) if params[:query][:location].present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def after_update_path_for(resource)
    if session[:redirect_to].present?
      url = session[:redirect_to]
      session[:redirect_to] = nil
      url
    else
      user_path(resource)
    end
  end

  def sign_up_params
   params.require(:user).permit(:email,
    :password,
    :password_confirmtaion,
    :current_password)
  end

  def account_update_params
    params.require(:user).permit(:first_name,
      :last_name,
      :nickname,
      :region,
      :departement,
      :address,
      :zipcode,
      :city,
      :phone,
      :birthdate,
      :password,
      :password_confirmtaion,
      :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end


  private
  def user_params
    params.require(:user).permit(:first_name,
      :last_name,
      :nickname,
      :region,
      :departement,
      :address,
      :zipcode,
      :city,
      :phone,
      :birthdate,
      :password,
      :password_confirmtaion,
      :current_password)
  end

end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adverts/_adverts.html.erb
<% @adverts.each do |advert| %>
  <% if advert.published? %>
    <div class="advert_frame">
      <%= link_to advert_path(advert) do  %>
        <div class="col-xs-10 col-xs-offset-1 advert">
          <div class="col-xs-4">
            <% advert.photos.each_with_index do |photo, index| %>
              <% if index == 0 %>
                <%= cl_image_tag photo.path, width: 200, height: 150, crop:"fill" %>
              <% end %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <h4> <%= advert.title %></h4>
            <p><%= advert.location %></p>
            <b><%= advert.price %>€</b>
          </div>
          <div class="col-xs-2">
            <i class="fa fa-heart"></i>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/adverts/_form.html.erb
<div class="row">
  <div class="col-xs-10 col-sm-10 col-sm-offset-1 padded">
    <%= simple_form_for(@advert) do |f| %>

      <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Type d'annonce" %>
      <%= f.select :role, User.roles.keys.to_a %>
      <%= f.select :role, Advert.roles.keys.to_a %>
      <%= f.input  :title, label: "Titre" %>
      <%= f.input  :description %>
      <%= f.input  :price, label: "Prix" %>
      <%= f.input  :location, label: "Localiasation" %>
      <%= f.input  :address, label: "Adresse" %>
      <%= f.input  :photos, as: :attachinary, hint: '3 photos max', label: false %>

      <%= f.button :submit %>

    <% end %>


  </div>
</div>

app/views/adverts/demandes.html.erb
<h1>Demandes</h1>

<%= render 'adverts' %>

app/views/adverts/edit.html.erb
<%= render :form %>

app/views/adverts/index.html.erb
<div class="col-xs-10 col-xs-offset-1 padded">
  <%= simple_form_for :query, url: adverts_path, method: :get,  wrapper: :inline_form, html: {class: 'form-inline'} do |f| %>
    <%= f.input  :category, collection: (Category.all.map {|c| c.name}) ,  prompt: "Choisissez une catégorie" %>
    <%= f.input  :keyword, placeholder: "Que cherchez-vous?" %>
    <%= f.input  :location, placeholder: "Cherchez par ville" %>
    <%= f.button :submit, "RECHERCHER", class:"btn btn-primary"  %>
  <% end %>
  </div>

<%= render 'adverts' %>

app/views/adverts/new.html.erb
<%= render 'form' %>

app/views/adverts/offers.html.erb
<h1>Annonces</h1>

<%= render 'adverts' %>

app/views/adverts/show.html.erb
<% if @advert.published? %>
<div class="col-xs-12">
  <h1><%= @advert.title %></h1>
  <p><%= @advert.description %></p>
  <h4><b><%= @advert.price %>€</b></h4>
  <h4><%= @advert.location %></h4>
  <% @advert.photos.each do |photo| %>
    <%= cl_image_tag photo.path, :transformation=>[
          {:width=>400, :height=>300, crop: :fill}] %>
  <% end %>
    <h4>Contacter le vendeur:</h4>
<ul class="list-unstyled">
  <li><%= @advert.user.phone %></li>
  <li><%= mail_to "envoyer un email", @advert.user.email %></li>
</ul>

</div>
<% end %>


<%= link_to "retour à la liste", adverts_path, class: "btn btn-primary"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeBonCoin</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
          <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Le Bon Coin", root_path %>

  <ul class="list-unstyled list-inline">
      <li><%= link_to  'DEPOSER UNE ANNONCE', new_advert_path %></li>
      <li><%= link_to  'OFFRES', offres_path %></li>
      <li><%= link_to  'DEMANDES', demandes_path %></li>
      <li><%= link_to  'MES ANNONCES', "#" %></li>
      <li><%= link_to  'BOUTIQUE', "#" %></li>
  </ul>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <h4 class="avatar dropdown-toggle", id="navbar-wagon-menu", data-toggle = "dropdown" ><%=current_user.nickname.present? ? current_user.nickname : current_user.email%></h4>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
  <h2>Mes données personnelles</h2>
  <h5><b>Prénom</b>:   <%= @user.first_name? ? @user.first_name : "N'a pas été renseigné" %></h5>
  <h5><b>Nom</b>:      <%= @user.last_name? ? @user.last_name : "N'a pas été renseigné" %></h5>
  <h5><b>Pseudo</b>:   <%= @user.nickname? ? @user.nickname : "N'a pas été renseigné" %></h5>
  <h5><b>Email</b>:    <%= @user.email? ? @user.email : "N'a pas été renseigné" %></h5>
  <h5><b>Région</b>:  <%= @user.region? ? @user.region : "N'a pas été renseigné" %></h5>
  <h5><b>Département</b>: <%= @user.departement? ? @user.departement : "N'a pas été renseigné" %></h5>
  <h5><b>Adresse</b>: <%= @user.address? ? present? : "N'a pas été renseigné" %></h5>
  <h5><b>Code Postal</b>: <%= @user.zipcode? ? @user.zipcode : "N'a pas été renseigné" %></h5>
  <h5><b>Ville</b>: <%= @user.city? ? @user.city : "N'a pas été renseigné" %></h5>
  <h5><b>Téléphone</b>: <%= @user.phone? ? @user.phone: "N'a pas été renseigné" %></h5>
  <h5><b>Date de naissance</b>: <%= @user.birthdate ? @user.birthdate : "N'a pas été renseigné" %></h5>

<% end %>

<%= link_to "Modifier", edit_user_registration_path, class:"btn btn-primary"  %>